spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?serverTimezone=UTC&charsetEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!@

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    secret: c3ByaW5nLWJvb3Qtc3RvcmUtcmVzZXJ2YXRpb24tcHJvamVjdC1qc29uLXdlYi10b2tlbi1zZWNyZXQta2V5